version: "3"

services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      - rail-docker
networks:
  rail-docker:
    driver: bridge
